# Generated by Django 5.2 on 2025-05-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pelaku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=256)),
                ('umur', models.CharField(max_length=256)),
                ('kasus', models.CharField(max_length=256)),
                ('tim_dukung', models.CharField(max_length=256)),
                ('foto_pelaku', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
