# Generated by Django 5.2 on 2025-05-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelaku',
            name='tanggal_berakhir',
            field=models.DateField(blank=True, null=True, verbose_name='Berlaku Hingga'),
        ),
        migrations.AddField(
            model_name='pelaku',
            name='tanggal_mulai',
            field=models.DateField(blank=True, null=True, verbose_name='Ditetapkan Pada'),
        ),
        migrations.AlterField(
            model_name='pelaku',
            name='foto_pelaku',
            field=models.ImageField(blank=True, null=True, upload_to='foto_pelaku/'),
        ),
    ]
